### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by aliya-rahmani**
Documented with proper description about the project and its function.

### CODE REVIEW

**Comment by someshnarwade** [comment]
@aliya-rahamani In the project link section you added the project link to this GitHub repository. The project like should take you to the project page on hyperskill.org website. Can you add the project link by searching for this project on hyperskill.org and then adding that link to Project Link in README.md?

**Comment by aliya-rahamani** [comment]
Okay, I'll do that.

**Comment by aliya-rahmani** [comment]
Is this the link?
link-  https://hyperskill.org/projects/109

**Comment by someshnarwade** [comment]
Yes, that's the link. Thank You for contributing to this project.

**Review by someshnarwade — APPROVED** [review]

**Pull request merged**
